apiVersion: apps/v1
kind: Deployment
metadata:
  name: mydeployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx-color
  template:
    metadata:
      labels:
        app: nginx-color
    spec:
      containers:
        - name: web
          image: kubedevio/nginx-color:blue
          resources:
            limits:
              memory: "128Mi"
              cpu: "500m"
          ports:
            - containerPort: 80
