apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-deploy
spec:
  replicas: 20
  selector:
    matchLabels:
      app: produto-api
  template:
    metadata:
      labels:
        app: produto-api
    spec:
      containers:
        - name: api
          image: naraguimma/api-produto:latest
          resources:
            limits:
              memory: "128Mi"
              cpu: "500m"
          ports:
            - containerPort: 8080
          env:
            - name: MONGODB_URI
              value: mongodb://mongouser:mongopwd@mongodb-service:27017/adim
